package prova;

public enum Token {
    CONSTANTE,
    INTEIRO,
    DECIMAL,
    PALAVRARESERVADA,
    TIPOVARIAVEL,
    RETORNODEFUNCAO,
    ATRIBUICAO,
    LOOPDEREPETICAO,
    INCREMENTO,
    OPERADORARITIMETICO,
    OPERADORCOMPARATIVO,
    OPERADORLOGICO,
    SIMBOLOESPECIAL,
    BRANCO,
    PALAVRACHAVE,
    NOME_VARIAVEL,
    ERROR;
}
